packages:
  - "apps/*"
allowBuilds:
  '@prisma/engines': true
  '@sentry/cli': true
  esbuild: true
  prisma: true
overrides:
  mysql2: ">=3.23.1"
  deepmerge-ts: ">=8.0.0"
  multer: ">=2.3.0"
  decode-uri-component: ">=0.5.0"
